# Day 3: Session 3A - Booleans & Conditionals

Date: 09/02/2026

In [2]:
import pandas as pd

url = "https://eds-217-essential-python.github.io/data/toolik_weather.csv"

toolik = pd.read_csv(url)

toolik.head()

,Year,Month,Date,LTER_Site,Station,Daily_AirTemp_Mean_C,Flag_Daily_AirTemp_Mean_C,Daily_AirTemp_AbsMax_C,Flag_Daily_AirTemp_AbsMax_C,Daily_AirTemp_AbsMin_C,...,Daily_Precip_Total_mm,Flag_Daily_Precip_Total_mm,Daily_windsp_mean_msec,FLAG_Daily_windsp_mean_msec,Daily_Windspeed_AbsMax_m_s,Daily_globalrad_total_jcm2,FLAG_Daily_globalrad_total_mjm2,Moss,Soil20cm,Comments
0,1988,6,19880601,ARC,TLKMAIN,8.4,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
1,1988,6,19880602,ARC,TLKMAIN,6.0,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
2,1988,6,19880603,ARC,TLKMAIN,5.8,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
3,1988,6,19880604,ARC,TLKMAIN,1.8,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
4,1988,6,19880605,ARC,TLKMAIN,6.8,E,NaN,NaN,NaN,...,2.5,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...

## 1. A yes-or-no question

In [3]:
temp = 8.4

In [4]:
type(temp > 0)

bool

In [5]:
above_freezing = temp > 0 
above_freezing

True

In [6]:
# How to find a specific row(s) in a dataframe:
toolik.loc[0] # OR
toolik.loc[[0, 1, 2]]
# .loc reaches into a dataframe and pulls out a row
# can give it an index number, name, or list of names or index numbers
rows_wanted = [0, 1, 2]
toolik.loc[rows_wanted]

,Year,Month,Date,LTER_Site,Station,Daily_AirTemp_Mean_C,Flag_Daily_AirTemp_Mean_C,Daily_AirTemp_AbsMax_C,Flag_Daily_AirTemp_AbsMax_C,Daily_AirTemp_AbsMin_C,...,Daily_Precip_Total_mm,Flag_Daily_Precip_Total_mm,Daily_windsp_mean_msec,FLAG_Daily_windsp_mean_msec,Daily_Windspeed_AbsMax_m_s,Daily_globalrad_total_jcm2,FLAG_Daily_globalrad_total_mjm2,Moss,Soil20cm,Comments
0,1988,6,19880601,ARC,TLKMAIN,8.4,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
1,1988,6,19880602,ARC,TLKMAIN,6.0,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...
2,1988,6,19880603,ARC,TLKMAIN,5.8,E,NaN,NaN,NaN,...,0.0,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Air temp 1 & 5 meter estimated from regressio...


## 2. The comparison operators

In [7]:
print(temp > 0)
print(temp < 0)
print(temp >= 0)
print(temp <= 0)
print(temp == 8.4) # needs to use == when asking "is this equal to?"
# single "=" is an assginment
print(temp != 8.4) # bang operator, "is not"

True
False
True
False
True
False

In [8]:
toolik.loc[0, 'Station'] # call a specific varible in row 0

'TLKMAIN'


## 3. Asking two questions at once

In [9]:
# plain Python vernacular includes "and", "or", "not"
temp = 8.4
precip = 0.0

print(temp > 0 and precip == 0.0) # "and" returns true when BOTH sides are true
print(temp > 0 or precip > 0.0) # "or" returns true if ONE side is true
print(not temp > 0) # "not" returns opposite of true/false

# can also use $ and/or | in some Python packages

True
True
False


## 4. if / elif / else

In [10]:
if temp > 0: # need a colon to trigger operation
    print("Below Freezing")
    # this indentation is how Python knows what's in a code block

Below Freezing

In [11]:
if temp > 0:
    print("Above Freezing")
else:
    print("Below Freezing")

Above Freezing

In [12]:
temp = -12.0
# elif combines else and if
# allows you to stack conditions and partition ranges

if temp > 10:
    category = 'hot'
elif temp > 5:
    category = 'mild'
elif temp > 0:
    category = 'cool'
elif temp > -5:
    category = 'cold'
else:
    category = 'brrrrr'
category

'brrrrr'


## 5. Asking a whole column

In [13]:
for value in toolik.loc[[0 ,5000, 2], "Daily_AirTemp_Mean_C"]:
    if value > 7:
        print(f"{value} is warm")
    elif value > 5: 
        print(f"{value} is mild")
    else:
        print(f"{value} is brrrr")

8.4 is warm
-26.1 is brrrr
5.8 is mild


## 6. Counting the Trues

In [14]:
above_zero = toolik['Daily_AirTemp_Mean_C'] > 0
above_zero.sum()

3817

In [15]:
# pure Python versus methods
print(above_zero.sum() / toolik.shape[0]) # methods

print(above_zero.sum() / len(toolik))

print(sum(above_zero) / len(toolik)) # pure Python

0.34168830006266226
0.34168830006266226
0.34168830006266226

## 7. Rules for **logical operators** and Dataframes/Series
### 1. Wrap every conitional in parentheses: ()
### 2. When doing "and"s and "or"s, we use "&" and "|"

In [19]:
# For example:
warm_and_dry = (toolik['Daily_AirTemp_Mean_C'] > 0) & (toolik['Daily_Precip_Total_mm'] == 0)
warm_and_dry

0         True
1         True
2         True
3         True
4        False
         ...
11166    False
11167    False
11168    False
11169    False
11170    False
Length: 11171, dtype: bool