# Day 2: Session 2B - Exploring a DataFrame

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2b_exploring_data.html)

Date: 09/01/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

In [2]:
goleta.tail() # .tail() does the opposite of .head() ! It calls the last number of rows

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
1957,1186,Goleta,pm25,10.0,µg/m³,2024-08-11T20:00:00+00:00,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1958,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T21:00:00+00:00,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1959,1186,Goleta,pm25,8.0,µg/m³,2024-08-11T22:00:00+00:00,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1960,1186,Goleta,pm25,9.0,µg/m³,2024-08-11T23:00:00+00:00,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1961,1186,Goleta,pm25,5.0,µg/m³,2024-08-12T00:00:00+00:00,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [3]:
# .shape gives you (rows, columns) 
goleta.shape # .shape is a **tupple**
# no "()" because position matters 
# and only returns 2 arguements

(1962, 15)

In [4]:
# Remember f strings
print(f"(rows, columns) = {goleta.shape}")

(rows, columns) = (1962, 15)

In [5]:
# .shape and .dtype is an ATTRIBUTE
goleta.dtypes

location_id        int64
location_name     object
parameter         object
value            float64
unit              object
datetimeUtc       object
datetimeLocal     object
timezone          object
latitude         float64
longitude        float64
country_iso      float64
isMobile         float64
isMonitor        float64
owner_name        object
provider          object
dtype: object

In [6]:
# .info() is a METHOD
# combines the shape, the column names, the types,
# AND how many non-null values each column has
goleta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    1962 non-null   int64
 1   location_name  1962 non-null   object
 2   parameter      1962 non-null   object
 3   value          1962 non-null   float64
 4   unit           1962 non-null   object
 5   datetimeUtc    1962 non-null   object
 6   datetimeLocal  1962 non-null   object
 7   timezone       1962 non-null   object
 8   latitude       1962 non-null   float64
 9   longitude      1962 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     1962 non-null   object
 14  provider       1962 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 230.1+ KB

In [7]:
goleta.isnull().sum() # asks the same question more directly

location_id         0
location_name       0
parameter           0
value               0
unit                0
datetimeUtc         0
datetimeLocal       0
timezone            0
latitude            0
longitude           0
country_iso      1962
isMobile         1962
isMonitor        1962
owner_name          0
provider            0
dtype: int64

In [8]:
url_sb = 'https://eds-217-essential-python.github.io/data/openaq_santa_barbara_measurments.csv'
santa_barbara = pd.read_csv(url_sb)
santa_barbara.info()
# same three columns are empty: country_iso, isMobile, isMonitor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2266 entries, 0 to 2265
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    2266 non-null   int64
 1   location_name  2266 non-null   object
 2   parameter      2266 non-null   object
 3   value          2266 non-null   float64
 4   unit           2266 non-null   object
 5   datetimeUtc    2266 non-null   object
 6   datetimeLocal  2266 non-null   object
 7   timezone       2266 non-null   object
 8   latitude       2266 non-null   float64
 9   longitude      2266 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     2266 non-null   object
 14  provider       2266 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 265.7+ KB

In [9]:
# To look up an object, call "?" first
# ?goleta.info
# can call a method definition, but must be an attribute, aka no "()"

In [10]:
# .describe() gives you count, mean, standard deviation, min, max, 
# and quartiles for every numeric column
goleta.describe()

# .describe() averages whatever numbers are in a column, 
# with no check on whether they belong together 
# therefore, grouping/mutating may be neccessary before calling .describe()

,location_id,value,latitude,longitude,country_iso,isMobile,isMonitor
count,1962.0,1962.000000,1.962000e+03,1.962000e+03,0.0,0.0,0.0
mean,1186.0,6.378173,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
std,0.0,7.313763,2.132172e-14,2.842896e-14,NaN,NaN,NaN
min,1186.0,-4.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
25%,1186.0,0.027000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
50%,1186.0,5.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
75%,1186.0,10.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN
max,1186.0,40.000000,3.444530e+01,-1.198278e+02,NaN,NaN,NaN

In [12]:
# .describe() is for numbers
# For text columns, the question is usually “what values appear, and how often?”
# .value_counts() is the answer
goleta['parameter'].value_counts()
# shows that parameter contains three different pollutants: pm25, o3, and pm10

parameter
pm25    734
o3      711
pm10    517
Name: count, dtype: int64

In [ ]:
## Renaming column with a dictionary
# A dictionary stores pairs. 
# Each pair has a key and a value, written "key:value" 
# and the whole thing goes in curly braces
new_names = {
    'datetimeUtc': 'datetime_utc',
    'datetimeLocal': 'datetime_local',
}
new_names
# A dictionary is a set of labelled pairs, and you call indv objects out of it by name

{'datetimeUtc': 'datetime_utc', 'datetimeLocal': 'datetime_local'}

In [ ]:
# This is the easiest way to rename columns
goleta_renamed = goleta.rename(columns=new_names)
goleta_renamed.columns.tolist()

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetime_utc',
 'datetime_local',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [20]:
goleta.rename(columns={'value': 'concentration'}).columns.tolist()

['location_id',
 'location_name',
 'parameter',
 'concentration',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [23]:
goleta_renamed = goleta.rename(columns={
    'value': 'concentration',
    'parameter' : 'pollutant'
    }).columns.tolist()
goleta_renamed

['location_id',
 'location_name',
 'pollutant',
 'concentration',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']