# Day 2: Session 2A - Reading Data into pandas

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2a_reading_data.html)

Date: 09/01/2026

In [26]:
import pandas as pd

In [1]:
url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)
goleta.head(4) # can insert a number into head() and it will return that number of rows
# indexes starting at 0, i.e. head(4) outputs 0:3

NameError: name 'pd' is not defined

In [16]:
url_sb = 'https://eds-217-essential-python.github.io/data/openaq_santa_barbara_measurments.csv'
santa_barbara = pd.read_csv(url_sb)
santa_barbara.head(4) # can insert a number into head() and it will return that number of rows
# indexes starting at 0, i.e. head(4) outputs 0:3

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,27499,Santa Barbara,o3,0.022,ppm,2024-07-11T01:00:00+00:00,2024-07-10T18:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T02:00:00+00:00,2024-07-10T19:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T03:00:00+00:00,2024-07-10T20:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,27499,Santa Barbara,o3,0.018,ppm,2024-07-11T04:00:00+00:00,2024-07-10T21:00:00-07:00,America/Los_Angeles,34.42775,-119.69091,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [17]:
goleta['value'] # pulling one **series** out of the dataframe
goleta['value'].head()

0    0.025
1    0.028
2    0.029
3    0.027
4    0.026
Name: value, dtype: float64

In [18]:
print(type(goleta)) # Dataframe
print(type(goleta['value'])) # Series

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [19]:
# Square brackets with one column name give you a Series. 
# Square brackets with a list of column names give you back a DataFrame, 
# even if the list has one item:

goleta['value']       # Returns a Series
goleta[['value']]     # Returns a DataFrame with one column

# OR, define the liste seperately
list_of_columns = ['value']
dataframe = goleta[list_of_columns]
type(dataframe)

pandas.core.frame.DataFrame

In [20]:
lat = goleta['latitude']       # Returns a Series
lat_lon = goleta[['latitude', 'longitude']]  
print(type(lat))
print(type(lat_lon))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [21]:
# .columns attribute gives you the names
goleta.columns

Index(['location_id', 'location_name', 'parameter', 'value', 'unit', 'datetimeUtc', 'datetimeLocal',
       'timezone', 'latitude', 'longitude', 'country_iso', 'isMobile', 'isMonitor', 'owner_name', 'provider'],
      dtype='object')

In [22]:
# The result is a pandas object rather than a plain Python list. 
# To get the list, which is easier to read and easier to work with, use .tolist()
column_names = goleta.columns.tolist()
column_names

# if you ever want to turn an object type into a different type ".to_Ex" usually does the trick
# ** .to_excel ** turns dataframes into excel spreadsheets

['location_id',
 'location_name',
 'parameter',
 'value',
 'unit',
 'datetimeUtc',
 'datetimeLocal',
 'timezone',
 'latitude',
 'longitude',
 'country_iso',
 'isMobile',
 'isMonitor',
 'owner_name',
 'provider']

In [23]:
# You can also get items out by position, counting from zero:
print(column_names[0])
print(column_names[1])

location_id
location_name

In [24]:
# The length function "len()" tells you how many ROWS there are in a dataframe
len(goleta)

1962

In [25]:
keep = ['location_name', 'parameter', 'value', 'unit'] # list of columns to keep
goleta[keep] # new dataframe with only listed columns

     location_name parameter   value   unit
0           Goleta        o3   0.025    ppm
1           Goleta        o3   0.028    ppm
2           Goleta        o3   0.029    ppm
3           Goleta        o3   0.027    ppm
4           Goleta        o3   0.026    ppm
...            ...       ...     ...    ...
1957        Goleta      pm25  10.000  µg/m³
1958        Goleta      pm25   8.000  µg/m³
1959        Goleta      pm25   8.000  µg/m³
1960        Goleta      pm25   9.000  µg/m³
1961        Goleta      pm25   5.000  µg/m³

[1962 rows x 4 columns]